declare module "lucide-react" {
  import { ForwardRefExoticComponent, RefAttributes, SVGProps } from "react";
  type SVGAttributes = Partial<SVGProps<SVGSVGElement>>;
  type ElementAttributes = RefAttributes<SVGSVGElement> & SVGAttributes;
  interface LucideProps extends ElementAttributes {
    size?: string | number;
    absoluteStrokeWidth?: boolean;
  }
  type LucideIcon = ForwardRefExoticComponent<Omit<LucideProps, "ref"> & RefAttributes<SVGSVGElement>>;
  export const Wand2: LucideIcon;
  export const Expand: LucideIcon;
  export const Minimize: LucideIcon;
  export const MessageSquareText: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Lightbulb: LucideIcon;
  export const ArrowLeftRight: LucideIcon;
  export const Check: LucideIcon;
  export const X: LucideIcon;
  export const Book: LucideIcon;
  export const Send: LucideIcon;
  export const Bot: LucideIcon;
  export const UserRound: LucideIcon;
  export const Loader2: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const Bolt: LucideIcon;
  export const PenLine: LucideIcon;
  export const Newspaper: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Eye: LucideIcon;
  export const Plus: LucideIcon;
  export const Star: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Clock3: LucideIcon;
  export const Clock: LucideIcon;
  export const Tag: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const History: LucideIcon;
  export const Trash2: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const Edit2: LucideIcon;
  export const Pencil: LucideIcon;
  export const Save: LucideIcon;
  export const Lock: LucideIcon;
  export const Unlock: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const ClipboardList: LucideIcon;
  export const ClipboardCopy: LucideIcon;
  export const Copy: LucideIcon;
  export const FileText: LucideIcon;
  export const Maximize2: LucideIcon;
  export const Maximize: LucideIcon;
  export const Minimize2: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Info: LucideIcon;
  export const CircleDashed: LucideIcon;
  export const Circle: LucideIcon;
  export const Link2: LucideIcon;
  export const Bookmark: LucideIcon;
  export const Pin: LucideIcon;
  export const Target: LucideIcon;
  export const CheckSquare2: LucideIcon;
  export const Zap: LucideIcon;
}
